import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';

export interface OrderItem {
  id: string;
  order_id: string;
  product_id: string | null;
  variation_id: string | null;
  title: string;
  price: number;
  quantity: number;
  created_at: string;
  product?: {
    id: string;
    slug: string;
    product_media?: { url: string }[];
  };
}

export interface Order {
  id: string;
  order_number: string;
  buyer_id: string;
  store_id: string;
  status: 'pending' | 'confirmed' | 'paid' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
  subtotal: number;
  shipping_cost: number;
  total: number;
  shipping_address: Record<string, string> | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
  paid_at: string | null;
  shipped_at: string | null;
  delivered_at: string | null;
  store?: {
    id: string;
    name: string;
    slug: string;
    logo_url: string | null;
  };
  buyer_profile?: {
    id: string;
    nome: string | null;
    email: string | null;
    avatar_url: string | null;
  };
  order_items?: OrderItem[];
}

export function useBuyerOrders() {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['buyer-orders', user?.id],
    queryFn: async () => {
      if (!user?.id) return [];

      const { data, error } = await supabase
        .from('orders')
        .select(`
          *,
          store:stores(id, name, slug, logo_url),
          order_items(
            id, order_id, product_id, title, price, quantity,
            product:products(id, slug, product_media(url))
          )
        `)
        .eq('buyer_id', user.id)
        .order('created_at', { ascending: false });

      if (error) throw error;
      return data as Order[];
    },
    enabled: !!user?.id,
  });
}

export function useStoreOrders(storeId: string, status?: string) {
  return useQuery({
    queryKey: ['store-orders', storeId, status],
    queryFn: async () => {
      let query = supabase
        .from('orders')
        .select(`
          *,
          order_items(
            id, order_id, product_id, title, price, quantity,
            product:products(id, slug, product_media(url))
          )
        `)
        .eq('store_id', storeId)
        .order('created_at', { ascending: false });

      if (status && status !== 'all') {
        query = query.eq('status', status as Order['status']);
      }

      const { data: orders, error } = await query;
      if (error) throw error;

      // Fetch buyer profiles
      const buyerIds = [...new Set(orders.map(o => o.buyer_id))];
      const { data: profiles } = await supabase
        .from('profiles')
        .select('id, nome, email, avatar_url')
        .in('id', buyerIds);

      return orders.map(order => ({
        ...order,
        buyer_profile: profiles?.find(p => p.id === order.buyer_id),
      })) as Order[];
    },
    enabled: !!storeId,
  });
}

export function useOrder(orderId: string) {
  return useQuery({
    queryKey: ['order', orderId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('orders')
        .select(`
          *,
          store:stores(id, name, slug, logo_url),
          order_items(
            id, order_id, product_id, title, price, quantity,
            product:products(id, slug, product_media(url))
          )
        `)
        .eq('id', orderId)
        .maybeSingle();

      if (error) throw error;

      if (data) {
        const { data: profile } = await supabase
          .from('profiles')
          .select('id, nome, email, avatar_url')
          .eq('id', data.buyer_id)
          .maybeSingle();

        return {
          ...data,
          buyer_profile: profile,
        } as Order;
      }

      return null;
    },
    enabled: !!orderId,
  });
}

export function useCreateOrder() {
  const queryClient = useQueryClient();
  const { user } = useAuth();

  return useMutation({
    mutationFn: async (data: {
      storeId: string;
      items: { productId: string; title: string; price: number; quantity: number; variationId?: string }[];
      shippingCost?: number;
      shippingAddress?: Record<string, string>;
      notes?: string;
    }) => {
      if (!user?.id) throw new Error('User not authenticated');

      const subtotal = data.items.reduce((sum, item) => sum + item.price * item.quantity, 0);
      const total = subtotal + (data.shippingCost || 0);

      // Create order
      const { data: order, error: orderError } = await supabase
        .from('orders')
        .insert({
          buyer_id: user.id,
          store_id: data.storeId,
          order_number: '', // Will be generated by trigger
          subtotal,
          shipping_cost: data.shippingCost || 0,
          total,
          shipping_address: data.shippingAddress || null,
          notes: data.notes || null,
          status: 'pending',
        })
        .select()
        .single();

      if (orderError) throw orderError;

      // Create order items
      const orderItems = data.items.map(item => ({
        order_id: order.id,
        product_id: item.productId,
        variation_id: item.variationId || null,
        title: item.title,
        price: item.price,
        quantity: item.quantity,
      }));

      const { error: itemsError } = await supabase
        .from('order_items')
        .insert(orderItems);

      if (itemsError) throw itemsError;

      return order as Order;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['buyer-orders'] });
    },
  });
}

export function useUpdateOrderStatus() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: {
      orderId: string;
      status: Order['status'];
    }) => {
      const updateData: Partial<Order> = { status: data.status };

      if (data.status === 'paid') {
        updateData.paid_at = new Date().toISOString();
      } else if (data.status === 'shipped') {
        updateData.shipped_at = new Date().toISOString();
      } else if (data.status === 'delivered') {
        updateData.delivered_at = new Date().toISOString();
      }

      const { data: order, error } = await supabase
        .from('orders')
        .update(updateData)
        .eq('id', data.orderId)
        .select()
        .single();

      if (error) throw error;
      return order as Order;
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ['order', variables.orderId] });
      queryClient.invalidateQueries({ queryKey: ['store-orders'] });
      queryClient.invalidateQueries({ queryKey: ['buyer-orders'] });
    },
  });
}
